namespace Mews.Fiscalization.Hungary.Dto
{
    public enum ErrorCode
    {
        INVALID_REQUEST = 1,
        INVALID_SECURITY_USER = 2,
        NOT_REGISTERED_CUSTOMER = 3,
        INVALID_CUSTOMER = 4,
        INVALID_USER_RELATION = 5,
        FORBIDDEN = 6,
        REQUEST_ID_NOT_UNIQUE = 7,
        INVALID_REQUEST_SIGNATURE = 8,
        INDEX_NOT_SEQUENTIAL = 9,
        INVALID_EXCHANGE_TOKEN = 10,
        REQUEST_VERSION_NOT_ALLOWED = 11,
        MAINTENANCE_MODE = 12,
        STATUS_QUERY_NOT_ALLOWED = 13,
        MULTIPLE_QUERY_RESULT_FOUND = 14,
        BAD_QUERY_PARAM_OVERLAP = 15,
        BAD_QUERY_PARAM_RANGE_EXCEEDED = 16,
        BAD_QUERY_PARAM_EQ_NOT_STANDALONE = 17,
        BAD_QUERY_PARAM_OPERATOR_COLLISION = 18,
        BAD_QUERY_PARAM_SUPPLIER_NOT_EXPECTED = 19
    }
}
